build:
	go build 1.go
	go build 2.go
	go build 3.go
	go build channel1.go
	go build channel2.go
	go build channel3.go
	go build channel4.go
	go build channel5.go
	go build channel6.go
clean:
	git clean  -fd
